# ==================================================================
#  
#  
#  _____            _   _ _____       _ _ _                _    
# |  __ \          | | (_)  __ \     | | | |              | |   
# | |  | | ___  ___| |_ _| |__) |___ | | | |__   __ _  ___| | __
# | |  | |/ _ \/ __| __| |  _  // _ \| | | '_ \ / _` |/ __| |/ /
# | |__| |  __/\__ \ |_| | | \ \ (_) | | | |_) | (_| | (__|   <
# |_____/ \___||___/\__|_|_|  \_\___/|_|_|_.__/ \__,_|\___|_|\_\
#  
#  
#  DestiRollBack is by iMrPop
#  
# ==================================================================
#  This is the Config that changes all the settings for this plugin
#  This is the documentation for all the Messages Below
# ==================================================================

AutoDelete:
  Enable: false
  GracePeriod: 30 #How Long will back ups be kept in days

# ==================================================================
#   __  __                  _
#  |  \/  | _  _  ___ __ _ | |
#  | |\/| || || |(_-</ _` || |
#  |_|  |_| \_, |/__/\__, ||_|
#           |__/        |_|
# ==================================================================

mysql:
  enable: false
  url: localhost
  username: root
  password: password
